/**
 * Source registry — every fact in the Atlas points to one of these entries.
 *
 * page      : printed page number in the white paper (as shown on the page)
 * pdfPage   : physical page in the 504-page PDF (printed page + 24 for the body)
 * section   : chapter path inside the white paper
 * label     : short human label for the source chip
 * excerpt   : verbatim text from the white paper (whitespace normalised).
 *             kind 'table' / 'figure' = cells joined with "｜", kind 'quote' = continuous text,
 *             "…" marks an omission inside a quote.
 *
 * Every excerpt is checked against the PDF text by scripts/verify-sources.mjs.
 */

export const DOCUMENT = {
  id: 'wp-2025-2026',
  title: '2025/2026產業技術白皮書',
  titleEn: '2025/2026 Industrial Technology White Paper',
  publisher: '經濟部產業技術司',
  publisherEn: 'Department of Industrial Technology, Ministry of Economic Affairs',
  published: '2025年9月',
  pages: 504,
  pageOffset: 24,
};

const SEC = {
  trends: '環境趨勢篇 › 壹、全球前瞻趨勢分析 › 一、全球重要趨勢與影響',
  domains: '環境趨勢篇 › 肆、我國重點產業需求與技術發展課題 › 二、重點領域的技術發展課題',
  toc: '目錄 › 產業技術篇',
  ictAI: '產業技術篇 › 參、資通訊領域 › 第二章 AI整合應用',
  ictHMI: '產業技術篇 › 參、資通訊領域 › 第三章 人機虛實互動',
  tool: '產業技術篇 › 肆、機械領域 › 第一章 工具機技術',
  robot: '產業技術篇 › 肆、機械領域 › 第二章 機器人',
  smfg: '產業技術篇 › 肆、機械領域 › 第三章 智慧製造',
};

// Front-matter (table of contents) pages use roman numerals.
const ROMAN = { III: 5, IV: 6, V: 7, VI: 8, VII: 9 };
const p = (page) => (typeof page === 'number' ? page + DOCUMENT.pageOffset : ROMAN[page]);

const entries = [
  // ───────────── L1 · Global trends ─────────────
  ['fig-1-1-1', 5, SEC.trends, '圖1-1-1 全球前瞻科技趨勢', 'figure',
    '圖1-1-1 全球2025~2035年前瞻科技趨勢與技術課題'],
  ['trend-social', 5, SEC.trends, '社會面趨勢', 'quote',
    '（一）社會面：強化人才循環機制滿足產業與市場需求'],
  ['trend-tech', 8, SEC.trends, '科技面趨勢', 'quote',
    '（二）科技面：AI、運算與通訊科技加速先進科技創新'],
  ['trend-tech-drivers', 8, SEC.trends, '科技面：關鍵因子', 'quote',
    '生成式AI(Generative AI, GAI)、運算科技和通訊科技的突破性進展，是驅動全球下世代科技創新的關鍵因子。'],
  ['trend-edge', 8, SEC.trends, '5G／6G 與邊緣運算', 'quote',
    '通訊科技方面，則隨著5G／第六代行動通訊系統(6th Generation Wireless Systems, 6G)網路的普及與滲透，實現低延遲、高頻寬的資料傳輸環境，持續推動邊緣運算(Edge Computing)與物聯網(Internet of Things, IoT)應用發展。'],
  ['trend-econ', 11, SEC.trends, '經濟面趨勢', 'quote',
    '（三）經濟面：「再全球化」尋求經濟與安全再平衡'],
  ['trend-env', 12, SEC.trends, '環境面趨勢', 'quote',
    '（四）環境面：「再全球化」造成全球的淨零腳步趨緩'],
  ['trend-pol', 15, SEC.trends, '政治面趨勢', 'quote',
    '（五）政治面：「川普2.0」與地緣政治格局變動'],
  ['tbl-1-1-2', 9, SEC.trends, '表1-1-2 AI 能力時間點預估', 'table',
    '表1-1-2 AI能力顯著超越人類表現的時間點預估｜感測與感知｜2030年｜2026年'],
  ['tbl-1-1-2-full', 9, SEC.trends, '表1-1-2（全表）', 'table',
    '表1-1-2 AI能力顯著超越人類表現的時間點預估｜創造力 2045年 2025年｜自然語言生成 2040年 2025年｜自然語言理解 2050年 2025年｜模式與類別生成 2029年 2025年｜感測與感知 2030年 2026年｜邏輯推理 2042年 2026年｜多代理協作 2035年 2027年｜社交與情緒生成 2035年 2030年｜社交與情緒感知 2045年 2030年｜社交與情緒推理 2048年 2030年｜資料來源：McKinsey Digital；資策會MIC整理，2025年5月。'],
  ['trend-breakthroughs', 9, SEC.trends, '未來5~10年突破領域', 'quote',
    '可預期未來5~10年，智慧系統、人機互動(Human-Machine Interaction, HMI)、人型機器人與太空科技等技術領域，將迎來突破性的進展。'],
  ['trend-smart-systems', 9, SEC.trends, '智慧系統：數位雙生與代理式AI', 'quote',
    '智慧系統方面，尤其是數位雙生(Digital Twin)與代理式AI(Agentic AI)，預計將成為全球科技創新的核心支柱。'],
  ['trend-dt', 9, SEC.trends, '數位雙生（趨勢）', 'quote',
    '數位雙生透過即時資料與AI模擬，創建實體世界的虛擬副本，可被廣泛應用於製造、城市與醫療等領域，大幅縮短產品開發週期'],
  ['trend-agentic', 9, SEC.trends, '代理式AI', 'quote',
    '代理式AI則是由諸多AI代理構成的協作網路，具備自主決策能力，甚至可根據環境變化自行調整任務執行方向與方式。'],
  ['trend-hmi', 9, SEC.trends, '人機互動 2D→3D', 'quote',
    '人機互動方面，則因應新型態AI協作需求，正在從傳統由鍵盤與螢幕構成的2D模式，轉向由擴增實境(Augmented Reality, AR)、虛擬實境(Virtual Reality, VR)與腦機介面(Brain-Computer Interface, BCI)等新興人機互動介面所構成的3D模式'],
  ['trend-humanoid', 10, SEC.trends, '人型機器人（趨勢）', 'quote',
    '人型機器人正在從實驗室走向商業應用，伴隨生成式AI的發展，將賦予機器人語言理解與環境適應能力，而HPC晶片和通訊科技的進展，則確保機器人能即時處理大量資料，並提升其運動控制與決策速度'],
  ['trend-humanoid-apps', 10, SEC.trends, '人型機器人應用與挑戰', 'quote',
    '預計未來人型機器人將廣泛應用於醫療照護、物流與家庭等領域，與智慧系統整合，推動自動化製造與個人化服務，成為人類生活的關鍵助手。主要挑戰則來自成本控制與安全性，尤其是在人機協作場域中的倫理議題。'],
  ['trend-space', 10, SEC.trends, '太空科技（趨勢）', 'quote',
    '太空科技在生成式AI、運算與通訊技術的推動下，正進入下一輪的快速發展期。'],

  // ───────────── L2 · Domains ─────────────
  ['dom-semi', 96, SEC.domains, '半導體及光電領域', 'quote',
    '（一）半導體及光電領域：高速運算與AI驅動半導體與顯示融合創新'],
  ['dom-ict', 100, SEC.domains, '資通訊領域', 'quote',
    '（二）資通訊領域：AI與衛星通訊驅動百工百業創新轉型發展'],
  ['dom-mech', 103, SEC.domains, '機械領域', 'quote',
    '（三）機械領域：AI驅動智慧製造與無人自主應用擴散'],
  ['dom-trans', 106, SEC.domains, '運輸領域', 'quote',
    '（四）運輸領域：智慧無人載具，開創安全、高效與移動新局'],
  ['dom-bio', 109, SEC.domains, '生醫領域', 'quote',
    '（五）生醫領域：數位科技與AI引領精準健康與創新發展'],
  ['dom-mat', 113, SEC.domains, '材化領域', 'quote',
    '（六）材化領域：AI助推循環製造，促進政策新材料發展'],
  ['dom-nz', 116, SEC.domains, '淨零科技領域', 'quote',
    '（七）淨零科技領域：潔淨能源與循環材料為全球綠色轉型趨勢'],
  ['mech-summary', 119, SEC.domains, '機械領域重要課題', 'quote',
    '機械領域：面對競爭與供應鏈重組，AI結合感測與通訊技術，推動智慧製造與無人自主系統發展，強化機器人與無人載具研發；在再全球化下，強調高價值工具機與整合製造方案創新，並透過數位轉型提升製造業韌性與永續競爭力。'],
  ['mech-tool-export', 103, SEC.domains, '工具機出口', 'quote',
    '工具機是我國機械業重要出口品項，2024年出口金額達22.1億美元'],
  ['mech-labor', 103, SEC.domains, '勞動力缺口', 'quote',
    '我國25~54歲勞動力人數預計2024~2030年將減少39.5萬人…，發展應用自動化方案與各類智慧機器人將是主要因應對策。'],
  ['mech-ai-robot', 103, SEC.domains, '感測＋AI 與機器人', 'quote',
    '近年來受惠於感測及資通訊元件效能進步，以及AI技術發展，讓智慧化機器人能透過訓練學習，快速具備執行多工能力，也更適合在複雜環境下作業'],
  ['mech-components', 105, SEC.domains, '智慧機器人：精密組件', 'quote',
    'A.精密組件：包含驅動馬達、精密減速機、螺桿、夾爪，以及多種力量、加速度、視覺、觸覺感測元件。此外，通訊、定位與導航，也是研發機器狗與人型機器人的重要元件。'],
  ['mech-brain', 105, SEC.domains, '智慧機器人：大腦與小腦', 'quote',
    'B.智慧控制：包含實現精密動作控制的「小腦」，用於理解人員命令與形成動作需求的「大腦」。這類裝置需要結合運算晶片及AI技術（如：生成式AI），也是發展具有實用性智慧機器人的重要挑戰。'],
  ['mech-si', 105, SEC.domains, '智慧機器人：系統整合', 'quote',
    'C.系統整合與測試驗證：除了滿足特定作業功能外，也要考量人員安全性及資通安全性，因此需要具備系統整合能力及完整的測試驗證方法。'],
  ['mech-smart-machine', 105, SEC.domains, '智慧化機台設備', 'quote',
    'A.智慧化機台設備：整合感測、物聯網、無線通訊（如：5G）、AI、數位雙生等，使機台與產線能提高產出效能、品質、長期運作穩定性與可用性'],
  ['mech-adaptive', 105, SEC.domains, '決策輔助與自適應', 'quote',
    'C.決策輔助與自適應：結合大數據及AI，讓製造系統在複雜的生產條件出現變化時，能提供適當分析資訊與決策建議給管理人員；結合生成式AI，更可進一步降低人員干預需求，提升機台與產線的自主應變能力。'],
  ['tbl-sense', 106, SEC.domains, '表1-4-3｜感測', 'table',
    '表1-4-3 機械領域之功能需求與核心科技｜感測：力量、加速度、觸覺、光學等先進感測｜精密機電元件設計，半導體製程，元件封裝測試'],
  ['tbl-act', 106, SEC.domains, '表1-4-3｜致動', 'table',
    '表1-4-3 機械領域之功能需求與核心科技｜致動：驅動馬達、精密減速機、滑軌、螺桿等致動元件｜精密機電元件設計，精密金屬加工、組裝'],
  ['tbl-dec', 106, SEC.domains, '表1-4-3｜分析與決策', 'table',
    '表1-4-3 機械領域之功能需求與核心科技｜分析與決策：運動控制，作業最佳化，人員指令理解，自主決策｜AI演算法，運算晶片設計製造'],
  ['tbl-si', 106, SEC.domains, '表1-4-3｜系統整合', 'table',
    '表1-4-3 機械領域之功能需求與核心科技｜系統整合：感知、通訊、人機介面、決策、致動、動力等系統功能整合與最佳化｜數位模擬，數位雙生，功能測試，系統工程'],
  ['trans-autonomy', 107, SEC.domains, '無人載具自主導航', 'quote',
    '透過AI驅動的感測技術實現自主導航、目標識別、自主避障等功能，並發展與其他無人載具間的協同控制與任務分配技術，使其能夠以集群方式高效執行大規模或複雜任務。'],
  ['ict-ai-needs', 102, SEC.domains, '產業 AI 應用需求', 'quote',
    'AI應用提供者可從行業領域的AI應用需求作為AI開發的考量點，像是金融業的客服、市場預測，或是製造業的瑕疵檢測、人機協作等'],

  // ───────────── TOC · chapters (with printed page numbers) ─────────────
  ['toc-semi', 'III', SEC.toc, '目錄：半導體及光電領域', 'figure',
    '第一章 先進製程與封裝 134｜第二章 化合物半導體 147｜第三章 半導體設備 160｜第四章 矽光子／量子科技 174｜第五章 面板科技 184'],
  ['toc-ict', 'IV', SEC.toc, '目錄：資通訊領域', 'figure',
    '第一章 次世代行動通訊 196｜第二章 AI整合應用 213｜第三章 人機虛實互動 223'],
  ['toc-mech', 'IV', SEC.toc, '目錄：機械領域', 'figure',
    '第一章 工具機技術 236｜第二章 機器人 252'],
  ['toc-mech-2', 'V', SEC.toc, '目錄：機械領域（續）', 'figure',
    '第三章 智慧製造 261'],
  ['toc-trans', 'V', SEC.toc, '目錄：運輸領域', 'figure',
    '第一章 智慧車輛 286｜第二章 無人載具 301'],
  ['toc-mat', 'VI', SEC.toc, '目錄：材化領域', 'figure',
    '第一章 材料開發及循環利用 374'],

  // ───────────── 圖1-1-1 全球2025~2035年前瞻科技趨勢與技術課題（p.5）─────────────
  // The ring labels are drawn as graphics, not text: transcribed from the rendered figure (visual: true).
  ['fig-ring', 5, SEC.trends, '圖1-1-1 五個面向與十大趨勢', 'figure',
    '社會面：都市化、高齡化｜科技面：超連接世界、虛實融合｜經濟面：數位轉型、跨界創新｜環境面：氣候變遷、能資源稀缺｜政治面：地緣政治、多極體系', true],
  ['fig-issues-social', 5, SEC.trends, '圖1-1-1 社會面課題', 'figure', '城市治理｜城鄉落差｜便利移動｜健康自立｜醫療照護｜無齡設施'],
  ['fig-issues-tech', 5, SEC.trends, '圖1-1-1 科技面課題', 'figure', '多重連接｜資訊安全｜科技治理｜基礎設施韌性｜沉浸體驗｜高速網路｜人機互動'],
  ['fig-issues-econ', 5, SEC.trends, '圖1-1-1 經濟面課題', 'figure', '產業轉型｜勞動力不足｜高齡再就業｜數位經濟｜新生活型態｜新型態工作'],
  ['fig-issues-env', 5, SEC.trends, '圖1-1-1 環境面課題', 'figure', '災防韌性｜糧食短缺｜生物多樣性｜全球傳染病｜淨零轉型｜循環經濟｜能資源效率｜綠色能源'],
  ['fig-issues-pol', 5, SEC.trends, '圖1-1-1 政治面課題', 'figure', '地緣政治｜公民參與｜網宇攻擊｜恐怖攻擊｜國家安全｜貿易壁壘｜供應鏈韌性'],
  ['fig-box-social', 5, SEC.trends, '圖1-1-1 技術課題（社會面）', 'figure',
    '智慧車輛｜無人載具｜智慧家庭｜智慧城市｜新藥｜醫療器材｜穿戴科技｜智慧醫療｜紡織科技｜再生醫學｜腦機介面｜智慧輔具'],
  ['fig-box-tech', 5, SEC.trends, '圖1-1-1 技術課題（科技面）', 'figure',
    '先進製程與封裝｜化合物半導體｜半導體設備｜矽光子／量子科技｜面板科技｜次世代行動通訊｜AI整合應用｜人機虛實互動｜運算基礎設施｜資安維護與風險管理'],
  ['fig-box-econ', 5, SEC.trends, '圖1-1-1 技術課題（經濟面）', 'figure',
    '工具機技術｜機器人｜智慧製造｜材料開發及循環利用｜積層製造（3D列印）｜感知與人體增強技術'],
  ['fig-box-env', 5, SEC.trends, '圖1-1-1 技術課題（環境面）', 'figure',
    '食品及生物資源｜材料開發與循環利用｜公衛防疫｜韌性基建｜氣象監測｜環境監控｜氫能應用｜先進電池｜再生能源｜產業減碳技術｜智慧儲能系統｜先進核能'],
  ['fig-box-pol', 5, SEC.trends, '圖1-1-1 技術課題（政治面）', 'figure',
    '太空科技｜衛星通訊與遙測｜公民科技｜軍事科技（實體戰／網路戰）'],

  // ───────────── ICT chapters (cross-domain) ─────────────
  ['ai-new-tech', 213, SEC.ictAI, 'AI整合應用：新興AI技術', 'quote',
    '從邊緣運算(Edge Computing)、生成式AI (Generative AI, GAI)、代理式AI(Agentic AI)到物理AI(Physical AI)，這些新興AI技術的推展，不僅帶動各行各業的智慧轉型，也緊密鏈結我國半導體產業的供應鏈協同創新能力。'],
  ['ai-edge-vision', 213, SEC.ictAI, '邊緣AI：即時影像辨識', 'quote',
    '利用邊緣AI實現即時影像辨識與設備監控'],
  ['ai-dual', 213, SEC.ictAI, 'AI產業化／產業AI化', 'quote',
    '明確提出「AI產業化」與「產業AI化」的雙重發展策略'],
  ['hmi-dt-key', 223, SEC.ictHMI, '數位雙生：智慧製造關鍵', 'quote',
    '整合IT、OT和AI技術的數位雙生(Digital Twin)，將成為智慧製造發展的關鍵'],
  ['hmi-omo', 223, SEC.ictHMI, '人機互動朝虛實融合', 'quote',
    '更加速各種應用及人機互動(Human-Machine Interaction, HMI)朝虛實融合(Online Merge Offline, OMO)的方向發展。'],
  ['dt-market', 226, SEC.ictHMI, '數位雙生市場', 'quote',
    '2022年全球數位雙生市場規模突破100億美元，預計2022年至2030年複合成長率為38.7%'],
  ['dt-focus', 226, SEC.ictHMI, '數位雙生發展重點', 'quote',
    '數位雙生作為實體世界的虛擬數位化映射，正迅速廣泛應用於半導體、電子、機械、金屬加工等產業，發展重點包括3D模擬建構、製程提升、AI運算管理，同時強調虛實融合網路及人機協同。'],
  ['dt-genai-3d', 226, SEC.ictHMI, '生成式AI建立3D模型', 'quote',
    '在數位雙生的應用中，首要挑戰是如何取得可於虛擬環境中運作的3D模型，涵蓋設備、機台與產線等。'],
  ['dt-edge', 227, SEC.ictHMI, '數位雙生仰賴邊緣運算', 'quote',
    '由於數位雙生須仰賴大量運算與即時感測資料，邊緣運算(Edge Computing)的低延遲優勢，以及智慧編排軟硬體資源的能力，成為推動應用落地的關鍵。'],
  ['industry-5', 227, SEC.ictHMI, '工業5.0與人機協作', 'quote',
    '相較於工業4.0著重於自動化、生產流程最佳化與數據驅動決策，工業5.0更關注以人為核心的協作模式，強調人類創造力與AI的協同整合。其核心理念在於實現人機協作、彈性製造與永續發展'],
  ['dt-arvr', 227, SEC.ictHMI, 'AR／VR 虛實互動', 'quote',
    '整合光機技術的擴增實境(Augmented Reality, AR)／虛擬實境(Virtual Reality, VR)眼鏡，也可以大幅提升使用者與系統的互動體驗，虛實互動技術亦可應用於設備組裝與校正情境，提升作業精度與效率'],
  ['dt-tsn', 227, SEC.ictHMI, 'TSN 同步控制', 'quote',
    '可導入TSN (Time-Sensitive Networking)技術，實現高精度時間校準與同步控制'],
  ['dt-definition', 228, SEC.ictHMI, '小知識：數位雙生', 'quote',
    '「數位雙生」是一種虛實整合技術，能同步模擬真實世界中的設備、系統或人員行為，常用於製造、交通、醫療等領域，以提升效率與決策精準度。'],
  ['digital-human', 228, SEC.ictHMI, '數位人物感知技術', 'quote',
    '透過「數位人物感知技術」整合作業人員的影像、生理數據與作業環境資訊，可建構高度擬真的虛擬數位人物，精準呈現作業行為模式，進而提供流程最佳化建議'],
  ['digital-human-ems', 228, SEC.ictHMI, '電子製造服務業案例', 'quote',
    '以電子製造服務業為例，針對大量人工組裝作業多仍仰賴經驗法則與靜態模擬，缺乏即時回饋與調整能力。'],
  ['digital-human-robot', 228, SEC.ictHMI, '數位人物與人形機器人', 'quote',
    '亦可強化人形機器人(Humanoid Robot)在導入實際場域前的行為學習與適應能力，改善過去人機協作策略不足的問題。'],
  ['dt-project', 229, SEC.ictHMI, '圖2-2-3-1 數位雙生研發藍圖', 'figure',
    '數位雙生關鍵技術研發與驗證（2025~2029年）｜執行單位：工業技術研究院、資訊工業策進會'],
  ['dt-roadmap-core', 229, SEC.ictHMI, '研發藍圖：兩大技術主軸', 'figure',
    '全場域數位系統生成與模擬技術開發｜虛實映射網路與數位人物感知技術開發'],
  ['dt-roadmap-dh', 229, SEC.ictHMI, '研發藍圖：數位人物', 'figure',
    '多模態感知系統｜數位分身動作暨組裝 SOP 生成框架｜數位分身AI行為模型精進'],
  ['dt-roadmap-hrc', 229, SEC.ictHMI, '研發藍圖：人機協同', 'figure',
    '人機協同組裝試產線｜人機協作應用的商業化驗證'],

  // ───────────── Machinery · Machine tool ─────────────
  ['tool-mother', 236, SEC.tool, '工具機總論', 'quote',
    '工具機為工業之母，對產業的重要性不言而喻。'],
  ['tool-targets', 236, SEC.tool, '工具機技術研發目標', 'quote',
    '目標鎖定五軸工具機空間精度及切削性能提升技術、綠智能工具機關鍵技術、工具機智慧零組件關鍵開發應用技術、工具機智動系統強健生產優化關鍵技術等'],
  ['tool-dt', 242, SEC.tool, '虛擬工具機數位雙生平台', 'quote',
    '科技專案建立虛擬工具機數位雙生平台，透過能耗輔助計算模組及能耗預測模型，真實呈現製程模擬和能耗最佳化'],
  ['tool-dt-agent', 243, SEC.tool, '數位雙生與AI代理', 'quote',
    '數位雙生由於其內涵符合特定物理現象的模擬機制，可用於驗證評價生成式AI模型所產生的文本、訊號、影音等資料，是一個開發AI代理的絕佳技術手段'],

  // ───────────── Machinery · Robot ─────────────
  ['robot-types', 252, SEC.robot, '機器人總論', 'quote',
    '機器人依應用，分為工業機器人與服務機器人兩大類。'],
  ['robot-service', 252, SEC.robot, '專業服務型機器人', 'quote',
    '專業服務型機器人（如：四足機器人、人型機器人等自主移動機器人）因其服務範圍及應用情境更偏向日常生活及複雜環境使用上，全球需求也逐年攀升，並應用於各式新興市場，如：巡檢、物品運輸、陪伴或是軍事應用。'],
  ['robot-humanoid-abilities', 252, SEC.robot, '人型機器人能力', 'quote',
    '現今所期待的人型機器人，是能夠具備語意理解、人機交互、自主決策等能力，來實現人類賦予它的任務'],
  ['robot-humanoid-parts', 252, SEC.robot, '人型機器人組件', 'quote',
    '人型機器人要具備大腦、小腦、機械臂、靈巧手、機器視覺等組件，實現對環境的感知交互、運動控制、任務執行'],
  ['robot-3-abilities', 252, SEC.robot, '感知・認知・動作', 'quote',
    '因此人型機器人需要強大的感知能力、認知能力、動作能力'],
  ['robot-balance', 252, SEC.robot, '雙足行走與關節', 'quote',
    '講求靈活彈性的人型機器人靠雙足行走，需要適應不同的地面，每個關節受力更加複雜，對減速機和馬達響應的速度要更快。'],
  ['robot-12-systems', 253, SEC.robot, '足式機器人12項核心系統', 'quote',
    '足式步行機器人的開發涉及12項核心系統，包括動力系統、控制系統、感知系統、AI、通訊群控系統及自主決策系統等關鍵領域'],
  ['robot-gap', 253, SEC.robot, '國內技術缺口', 'quote',
    '國內廠商具有一定的系統整合(System Integration, SI)能力，但尚未具備高階感測模組及動力系統的自主開發能力。'],
  ['robot-attitude-power', 253, SEC.robot, '姿態感知與動力系統', 'quote',
    '自主姿態融合感知技術的應用仍面臨核心感測元件依賴進口姿態感測模組的問題，而動力系統則是須發展整合結構、減速機、馬達、驅動器與編碼器成一體化設計。'],
  ['robot-projects', 253, SEC.robot, '圖2-3-2 機器人相關研發計畫', 'figure',
    '機器人2.0+諧作化智造系統開發及應用計畫／工研院、精機中心｜晶片驅動精準農業之晶片創新與關鍵模組研發計畫／工研院｜農工智慧轉型關鍵協作與示範計畫／工研院'],
  ['smart-factory-market', 255, SEC.robot, '智慧工廠市場', 'quote',
    '智慧工廠市場規模預計2029年將達到5,643.8億美元，複合年成長率為9.74%（2024~2029年）。'],
  ['robot-ifr', 255, SEC.robot, 'IFR 2025年報告', 'quote',
    '另根據國際機器人聯合會(International Federation of Robotics, IFR) 2025年報告'],
  ['robot-ifr-market', 255, SEC.robot, 'IFR 2025 工業機器人市場', 'quote',
    '全球工業機器人市場規模預估為165億美元，全球工廠中運作的工業機器人更高達400萬台。'],
  ['robot-ifr-trends', 255, SEC.robot, 'IFR 機器人五大趨勢', 'quote',
    '一、AI機器人：利用多種AI技術，機器人可以理解複雜的任務，並有效率地執行各種工作；二、人形機器人：硬體算力的大幅提升，使人形機器人有機會能落地應用'],
  ['smart-3-steps', 256, SEC.robot, '智慧製造三個進程', 'quote',
    '打造智慧製造工廠需要遵循三個推動進程，自動化→數位化→智慧化（智造化）。'],
  ['robot-in-mfg', 256, SEC.robot, '機器人與智慧製造', 'quote',
    '自動化和機器人技術是實現智慧製造的關鍵因素。機器人的導入，可以減少人為錯誤，提高生產效率和產品品質。'],
  ['virtual-sim', 256, SEC.robot, '高擬真虛實融合（虛擬仿真）', 'quote',
    '高擬真虛實融合（虛擬仿真）是建立智慧工廠的另一項關鍵。此技術使製造業可以在虛擬環境中模擬各種狀況並獲得最佳製造方案，減少試誤成本和時間並確保生產過程的穩定和高效。'],
  ['omo-platform', 256, SEC.robot, 'OMO 平台賦能機器人', 'quote',
    '高擬真虛實融合(Online Merge Offline, OMO)平台技術結合可賦能機器人，以擬真模擬、AI分析與機器人單一化控制器等技術，建立機器人與產線間快速整合、提升產線自動化與智慧化程度'],
  ['omo-industries', 256, SEC.robot, 'OMO 導入產業', 'quote',
    '擴大導入至國內各行各業（工具機、PCB、金屬加工、半導體、手工具、汽機車零件、廚具、精品刀具、自行車等）'],
  ['fixture-free', 256, SEC.robot, '高擬真仿人類雙手協作機器人', 'quote',
    '目標是機器人在不使用治具的條件下（現有機器人都必須搭配治具才能執行組裝任務），利用AI演算法自動生成組裝程序，精準模仿板手組裝技師的操作動作，進行大小樣式不同的板手組裝（超過120種手工具）。'],
  ['horizon', 256, SEC.robot, 'Horizon Europe 成果', 'quote',
    '參與歐盟科學研究計畫（Horizon Europe，計畫時程2023~2025年）之成果「高擬真仿人類雙手協作機器人」'],
  ['fixture-partner', 256, SEC.robot, '手工具產業合作', 'quote',
    '目前已與國內手工具界的隱形冠軍「英發企業」合作，助攻臺灣手工具產業保持全球領先地位。'],
  ['holon-startup', 256, SEC.robot, '新創案例：赫侖', 'quote',
    '新創公司「赫侖」所開發的Holon OS是一款工業機器人智慧製造核心軟體'],
  ['holon-os', 256, SEC.robot, '單一化控制器（Holon OS）', 'quote',
    'Holon OS以單一化控制器技術概念，支援控制國內外各大廠牌機器人，解決了機器人跨廠牌整合及製程工藝資料管理的困難，提高生產靈活度及效率，滿足彈性生產需求。'],
  ['holon-path', 256, SEC.robot, 'AI 生成工作路徑', 'quote',
    '它透過AI自動生成機器人最佳工作路徑、即時補償變異。'],
  ['rm-fixture', 257, SEC.robot, '研發藍圖：虛擬治具組裝', 'figure',
    '虛擬治具組裝技術，三種不同型態，組裝成功率>95%'],
  ['rm-force', 257, SEC.robot, '研發藍圖：位力協作控制', 'figure',
    '位力協作控制技術，控制精度達0.5 mm'],
  ['rm-hrc', 257, SEC.robot, '研發藍圖：人機異質協作', 'figure',
    '人機異質協作技術，支援二種人機協作情境'],
  ['rm-cog', 257, SEC.robot, '研發藍圖：重心調整', 'figure',
    '機器人重心調整技術，可應用地面起伏不定的環境（5度內）'],
  ['rm-balance', 257, SEC.robot, '研發藍圖：自平衡控制', 'figure',
    '機器人自平衡控制技術，雙臂負荷20 Kg仍可透過維持重心'],
  ['rm-multi', 257, SEC.robot, '研發藍圖：多機器人遠距協作', 'figure',
    '支援半導體場域，多機器人遠距協作提升效率30%'],
  ['rm-xr', 257, SEC.robot, '研發藍圖：AR/VR/MR 導引', 'figure',
    '人機作業AI偵測與導引／流程自動化技術，可結合三種沉浸式體驗介面(AR/VR/MR)，提升工作效率30%以上'],
  ['rm-rl', 257, SEC.robot, '研發藍圖：虛實互動學習', 'figure',
    '虛實整合人機互動協作控制／虛擬互動反向加強式學習技術，可應用於醫院場所之任務工作規劃（至少三種任務）'],
  ['rm-energy', 257, SEC.robot, '研發藍圖：能耗預測', 'figure',
    '機器人運轉效率預測技術，能耗模型預測準確度>80%'],
  ['rm-apps', 257, SEC.robot, '研發藍圖：產業應用', 'figure',
    '產業應用｜PCB｜金屬加工｜半導體｜機械設備｜醫療'],
  ['rm-assistant', 257, SEC.robot, '研發藍圖：機器人助手', 'figure',
    '領域數位知識與機器人助手整合協作技術，提高機器設備稼動率30%以上'],
  ['robot2-project', 257, SEC.robot, '機器人2.0＋計畫', 'figure',
    '機器人2.0＋諧作化智造系統開發及應用計畫（2024~2027年）｜執行單位：工業技術研究院、精密機械研究發展中心'],
  ['smart-mfg-def', 257, SEC.robot, '小知識：智慧製造', 'quote',
    '智慧製造係指整合科技與數位技術於製造業的概念，大致作法是利用機器人、感知融合、數據分析、自動化和AI等先進技術，實現提高生產效率、品質、彈性生產等目標。'],
  ['agri-core', 258, SEC.robot, '晶片驅動精準農業', 'quote',
    '以國產低功耗邊緣運算晶片、智慧感測與驅動逆變器(Inverter)技術為核心，推動自主移動機器人(Autonomous Mobile Robot, AMR)於授粉、採摘與巡檢等應用系統之開發。'],
  ['agri-market', 258, SEC.robot, '精準農業市場', 'quote',
    '全球精準農業市場規模預計將從2023年的97億美元成長到2031年的219億美元，2023年至2031年期間的複合年增長率為10.7%'],
  ['agri-edge-key', 258, SEC.robot, '低功耗晶片與邊緣運算', 'quote',
    '特別是低功耗、高效率的晶片與AI邊緣運算(Edge Computing)技術，將成為未來農業升級的關鍵。'],
  ['agri-dla', 259, SEC.robot, '國產AI邊緣運算晶片模組', 'quote',
    '本專案將開發適用農業場域的國產AI邊緣運算晶片模組，結合高效能深度學習加速器(Deep Learning Accelerator, DLA)設計，加速模型推論並成功突破模型運算延遲與能耗的限制，使模型推論影像更新率達30 fps以上、辨識精度提升至85%以上'],
  ['agri-lightweight', 259, SEC.robot, '模型輕量化', 'quote',
    '針對授粉花朵與小番茄果實辨識等場域，達成邊緣端即時高精度辨識，大幅改善過往推動生產智慧化過程須面對的通訊與控制問題。'],
  ['agri-amr', 259, SEC.robot, 'AMR 共通載具', 'quote',
    'AMR共通載具整合了定位導航、路徑規劃與作業控制'],
  ['agri-tomato', 259, SEC.robot, '授粉與採摘機器人', 'quote',
    '機器人搭載國產邊緣AI運算邏輯晶片，可即時辨識番茄花與果實，執行擾動授粉與精準採摘作業'],
  ['agri-apps', 259, SEC.robot, '延伸應用場域', 'quote',
    '也可應用於果園巡檢、自動病蟲害辨識、禽舍異常行為辨識與即時通報等場域。'],
  ['agri-aqua', 259, SEC.robot, '智慧養殖', 'quote',
    '結合影像辨識與水質感測技術，實現魚群活動偵測與智慧餌料投放控制'],
  ['agri-biz', 259, SEC.robot, '新商業模式', 'quote',
    '「晶片模組設計＋農工機器人製造＋場域服務」之新商業模式'],
  ['agri-roadmap-chip', 260, SEC.robot, '研發藍圖：邊緣運算模組', 'figure',
    '完成國產AI邊緣運算模組雛型整合｜MTK Genio與DLA｜FPS ≥30｜精準度≥85%'],
  ['agri-roadmap-dual', 260, SEC.robot, '研發藍圖：雙機器人協作', 'figure',
    '雙機器人協作系統整合｜系統整合延遲 ≤100 ms｜作業效率≥20%'],
  ['agri-projects', 260, SEC.robot, '精準農業相關科專', 'figure',
    '晶片驅動精準農業之晶片創新與關鍵模組研發計畫（2024~2028年）｜農工智慧轉型關鍵協作與示範計畫（2023~2026年）｜執行單位：工業技術研究院'],

  // ───────────── Machinery · Smart manufacturing ─────────────
  ['smfg-focus', 261, SEC.smfg, '智慧製造總論', 'quote',
    '經濟部產業技術司主責智慧製造關鍵技術研發，藉由產學研能量整合，聚焦智慧設備、AI生產與智慧加工模組等重點領域。'],
  ['smfg-tech', 261, SEC.smfg, '智慧製造技術布局', 'quote',
    '技術布局面向亦涵蓋「智慧工廠AI加值與數位系統開發技術」、「虛實整合智慧製造產線數位內容生成技術」及「自適應人工智慧生產決策技術」'],
  ['smfg-fusion', 265, SEC.smfg, '多感測器數據融合', 'quote',
    '多感測器數據融合技術：能即時監控與分析製程中的多重參數，精確識別設備異常狀態'],
  ['smfg-aoi', 265, SEC.smfg, 'AI 輔助自動光學檢測', 'quote',
    '針對產品品質檢測常見以AI來輔助提升自動光學檢測之功效'],
];

export const SOURCES = Object.fromEntries(
  entries.map(([id, page, section, label, kind, excerpt, visual = false]) => [
    id,
    { id, page, pdfPage: p(page), section, label, kind, excerpt, visual },
  ]),
);

export const getSource = (id) => SOURCES[id];
